version: '3'
services: 
  frontend:
    container_name: chatbot-front
    build: front-end/web-chatbot
    restart: on-failure
    ports: 
      - 5173:5173    
    volumes:
      - ./front-end/web-chatbot/src:/app-frontend/src
    depends_on:
      - backend
  backend:
    container_name: chatbot-back
    build: back-end/
    restart: on-failure
    ports: 
      - 3001:3001    
    volumes:
      - ./back-end/:/app-backend/
    depends_on:
      - database
  database:
    build:
      context: .
      dockerfile: Dockerfile.mysql
    container_name: mysql-container    
    ports:
      - 3306:3306
    

