DROP DATABASE IF EXISTS Chatbot;

CREATE DATABASE Chatbot;

USE Chatbot;

CREATE TABLE users (
  id INT NOT NULL auto_increment,
  name VARCHAR(30) NOT NULL,
  password VARCHAR(30) NOT NULL,
  PRIMARY KEY(id)
);

SET SQL_SAFE_UPDATES = 0;